---
title: "Guidebook"
author: "Ryan Melnick"
date: "12/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# need to change file path to be able to read in tmall.RDS on your computer
data <- readRDS('~/Downloads/tmall.RDS')

# note that any 4fb with SpinAxis below 130 is most likely 2fb

install.packages("dplyr")    # alternative installation of the %>%
library(dplyr)    # alternatively, this also loads %>%
library(tidyverse)
```


```{r}
# Cleaning Up Data - Unifying pitches by pitch type to have the same tag
data <- data %>% mutate(TaggedPitchType = ifelse(TaggedPitchType == "Fastball", "FF", TaggedPitchType))
data <- data %>% mutate(TaggedPitchType = ifelse(TaggedPitchType == "Sinker", "FT", TaggedPitchType))
data <- data %>% mutate(TaggedPitchType = ifelse(TaggedPitchType == "FB", "FF", TaggedPitchType))
data <- data %>% mutate(TaggedPitchType = ifelse(TaggedPitchType == "Slider", "SL", TaggedPitchType))
data <- data %>% mutate(TaggedPitchType = ifelse(TaggedPitchType == "Curveball", "CB", TaggedPitchType))
data <- data %>% mutate(TaggedPitchType = ifelse(TaggedPitchType == "Changeup", "CH", TaggedPitchType))
data <- data %>% mutate(TaggedPitchType = ifelse(TaggedPitchType == "ChangeUp", "CH", TaggedPitchType))
data <- data %>% mutate(TaggedPitchType = ifelse(TaggedPitchType == "Cutter", "CT", TaggedPitchType))
data <- data %>% mutate(TaggedPitchType = ifelse(TaggedPitchType == "Knuckleball", "KN", TaggedPitchType))
data <- data %>% mutate(TaggedPitchType = ifelse(TaggedPitchType == "Splitter", "SPL", TaggedPitchType))


data <- data %>% mutate(AutoPitchType = ifelse(AutoPitchType == "Fastball", "FF", AutoPitchType))
data <- data %>% mutate(AutoPitchType = ifelse(AutoPitchType == "Sinker", "FT", AutoPitchType))
data <- data %>% mutate(AutoPitchType = ifelse(AutoPitchType == "FB", "FF", AutoPitchType))
data <- data %>% mutate(AutoPitchType = ifelse(AutoPitchType == "Slider", "SL", AutoPitchType))
data <- data %>% mutate(AutoPitchType = ifelse(AutoPitchType == "Curveball", "CB", AutoPitchType))
data <- data %>% mutate(AutoPitchType = ifelse(AutoPitchType == "Changeup", "CH", AutoPitchType))
data <- data %>% mutate(AutoPitchType = ifelse(AutoPitchType == "ChangeUp", "CH", AutoPitchType))
data <- data %>% mutate(AutoPitchType = ifelse(AutoPitchType == "Cutter", "CT", AutoPitchType))
data <- data %>% mutate(AutoPitchType = ifelse(AutoPitchType == "Knuckleball", "KN", AutoPitchType))
data <- data %>% mutate(AutoPitchType = ifelse(AutoPitchType == "Splitter", "SPL", AutoPitchType))
data <- data %>% mutate(AutoPitchType = ifelse(AutoPitchType == "Four-Seam", "FF", AutoPitchType))
```


```{r}
table(data$TaggedPitchType)

table(data$AutoPitchType)
```


```{r}
wake <- subset(data, PitcherTeam == "WAK_DEA")

table(wake$TaggedPitchType)
table(wake$AutoPitchType)


WakePitchers <- subset(wake, select = c("Date", "Pitcher", "PitcherId", "PitcherThrows", "PitcherTeam", "Batter", "BatterId", "BatterSide", "BatterTeam", "Inning", "Outs", "Balls", "Strikes", "TaggedPitchType", "AutoPitchType", "PitchCall", "KorBB", "HitType", "PlayResult", "OutsOnPlay", "RunsScored", "RelSpeed", "VertRelAngle", "HorzRelAngle", "SpinRate", "SpinAxis", "RelHeight", "RelSide", "Extension", "InducedVertBreak", "HorzBreak", "PlateLocHeight", "PlateLocSide", "ZoneSpeed", "VertApprAngle", "HorzApprAngle", "ZoneTime", "ExitSpeed", "Angle", "pfxx", "pfxz", "PitchUID", "SpinEff", "TrueSpin"))
```


```{r}
## Wake RHP FF
WAKE_RHP_FF <- subset(WakePitchers, TaggedPitchType == "FF" & PitcherThrows == "Right" & SpinAxis < 225 & SpinAxis > 165 & RelSpeed > 75 & InducedVertBreak > -3)

## Wake LHP FF
WAKE_LHP_FF <- subset(WakePitchers, TaggedPitchType == "FF" & PitcherThrows == "Left" & RelSpeed > 80 & SpinAxis > 135 & SpinAxis < 195 & InducedVertBreak > -3)

## Wake RHP FT
WAKE_RHP_FT <- subset(WakePitchers, (TaggedPitchType == "FT" | (TaggedPitchType == "FF" & SpinAxis > 225)) & PitcherThrows == "Right" & SpinAxis > 225 & RelSpeed > 75 & InducedVertBreak > -3)

## Wake LHP FT
WAKE_LHP_FT <- subset(WakePitchers, (TaggedPitchType == "FT" | (TaggedPitchType == "FF" & SpinAxis < 135)) & PitcherThrows == "Left" & SpinAxis < 135 & RelSpeed > 75 & InducedVertBreak > -3)

## Wake RHP SL
WAKE_RHP_SL <- subset(WakePitchers, TaggedPitchType == "SL" & PitcherThrows == "Right" & (SpinAxis < 200 | SpinAxis > 300) & HorzBreak < 7 & RelSpeed > 65)

## Wake LHP SL
WAKE_LHP_SL <- subset(WakePitchers, TaggedPitchType == "SL" & PitcherThrows == "Left" & (SpinAxis > 180 | SpinAxis < 135) & HorzBreak > -7)

## Wake RHP CB
WAKE_RHP_CB <- subset(WakePitchers, TaggedPitchType == "CB" & PitcherThrows == "Right" & RelSpeed < 90 & (SpinAxis < 135 | SpinAxis > 195) & InducedVertBreak < 3 & HorzBreak < 5)

## Wake LHP CB
WAKE_LHP_CB <- subset(WakePitchers, TaggedPitchType == "CB" & PitcherThrows == "Left" & InducedVertBreak < 3 & HorzBreak > -5 & (SpinAxis < 165 | SpinAxis > 262.5))

## Wake RHP CH
WAKE_RHP_CH <- subset(WakePitchers, TaggedPitchType == "CH" & PitcherThrows == "Right" & RelSpeed > 65 & SpinAxis > 165 & SpinAxis < 330)

## Wake LHP CH
WAKE_LHP_CH <- subset(WakePitchers, TaggedPitchType == "CH" & PitcherThrows == "Left" & RelSpeed > 65 & (SpinAxis < 195 | SpinAxis > 65))

## Wake RHP CT
WAKE_RHP_CT <- subset(WakePitchers, TaggedPitchType == "CT" & PitcherThrows == "Right")

## Wake LHP CT
WAKE_LHP_CT <- subset(WakePitchers, TaggedPitchType == "CT" & PitcherThrows == "Left")
```


```{r}
ACCSEC <- subset(data, PitcherTeam == "WAK_DEA" | PitcherTeam == "BOC_EAG" | PitcherTeam == "CLE_TIG" | PitcherTeam == "DUK_BLU" | PitcherTeam == "FLO_SEM" | PitcherTeam == "GIT_YEL" | PitcherTeam == "LOU_CAR" | PitcherTeam == "MIA_HUR" | PitcherTeam == "NOR_TAR" | PitcherTeam == "NOR_WOL" | PitcherTeam == "NOT_IRI" | PitcherTeam == "PIT_PAN" | PitcherTeam == "VIR_CAV" | PitcherTeam == "VT" | PitcherTeam == "VIR_TEC" | PitcherTeam == "ALA_CRI" | PitcherTeam == "ARK_RAZ" | PitcherTeam == "AUB_TIG" | PitcherTeam == "FLO_GAT" | PitcherTeam == "GEO_BUL" | PitcherTeam == "KEN_WIL" | PitcherTeam == "LSU_TIG" | PitcherTeam == "OLE_REB" | PitcherTeam == "MSU_BDG" | PitcherTeam == "MIZ_TIG" | PitcherTeam == "SOU_GAM" | PitcherTeam == "TEN_VOL" | PitcherTeam == "TEX_AGG" | PitcherTeam == "VAN_COM")

ACCSECPitchers <- subset(ACCSEC, select = c("Date", "Pitcher", "PitcherId", "PitcherThrows", "PitcherTeam", "Batter", "BatterId", "BatterSide", "BatterTeam", "Inning", "Outs", "Balls", "Strikes", "TaggedPitchType", "AutoPitchType", "PitchCall", "KorBB", "HitType", "PlayResult", "OutsOnPlay", "RunsScored", "RelSpeed", "VertRelAngle", "HorzRelAngle", "SpinRate", "SpinAxis", "RelHeight", "RelSide", "Extension", "InducedVertBreak", "HorzBreak", "PlateLocHeight", "PlateLocSide", "ZoneSpeed", "VertApprAngle", "HorzApprAngle", "ZoneTime", "ExitSpeed", "Angle", "pfxx", "pfxz", "PitchUID", "SpinEff", "TrueSpin"))

table(ACCSEC$TaggedPitchType)
table(ACCSEC$AutoPitchType)
```


```{r}
## ACCSEC RHP FF
ACCSEC_RHP_FF <- subset(ACCSECPitchers, TaggedPitchType == "FF" & PitcherThrows == "Right" & SpinAxis < 225 & SpinAxis > 165 & RelSpeed > 75 & InducedVertBreak > -3)

## ACCSEC LHP FF
ACCSEC_LHP_FF <- subset(ACCSECPitchers, TaggedPitchType == "FF" & PitcherThrows == "Left" & RelSpeed > 80 & SpinAxis > 135 & SpinAxis < 195 & InducedVertBreak > -3)

## ACCSEC RHP FT
ACCSEC_RHP_FT <- subset(ACCSECPitchers, (TaggedPitchType == "FT" | (TaggedPitchType == "FF" & SpinAxis > 225)) & PitcherThrows == "Right" & SpinAxis > 225 & RelSpeed > 75 & InducedVertBreak > -3)

## ACCSEC LHP FT
ACCSEC_LHP_FT <- subset(ACCSECPitchers, (TaggedPitchType == "FT" | (TaggedPitchType == "FF" & SpinAxis < 135)) & PitcherThrows == "Left" & SpinAxis < 135 & RelSpeed > 75 & InducedVertBreak > -3)

## ACCSEC RHP SL
ACCSEC_RHP_SL <- subset(ACCSECPitchers, TaggedPitchType == "SL" & PitcherThrows == "Right" & (SpinAxis < 200 | SpinAxis > 300) & HorzBreak < 7 & RelSpeed > 65)

## ACCSEC LHP SL
ACCSEC_LHP_SL <- subset(ACCSECPitchers, TaggedPitchType == "SL" & PitcherThrows == "Left" & (SpinAxis > 180 | SpinAxis < 135) & HorzBreak > -7)

## ACCSEC RHP CB
ACCSEC_RHP_CB <- subset(ACCSECPitchers, TaggedPitchType == "CB" & PitcherThrows == "Right" & RelSpeed < 90 & (SpinAxis < 135 | SpinAxis > 195) & InducedVertBreak < 3 & HorzBreak < 5)

## ACCSEC LHP CB
ACCSEC_LHP_CB <- subset(ACCSECPitchers, TaggedPitchType == "CB" & PitcherThrows == "Left" & InducedVertBreak < 3 & HorzBreak > -5 & (SpinAxis < 165 | SpinAxis > 262.5))

## ACCSEC RHP CH
ACCSEC_RHP_CH <- subset(ACCSECPitchers, TaggedPitchType == "CH" & PitcherThrows == "Right" & RelSpeed > 65 & SpinAxis > 165 & SpinAxis < 330)

## ACCSEC LHP CH
ACCSEC_LHP_CH <- subset(ACCSECPitchers, TaggedPitchType == "CH" & PitcherThrows == "Left" & RelSpeed > 65 & SpinAxis < 195 & SpinAxis > 65)

## ACCSEC RHP CT
ACCSEC_RHP_CT <- subset(ACCSECPitchers, TaggedPitchType == "CT" & PitcherThrows == "Right")

## ACCSEC LHP CT
ACCSEC_LHP_CT <- subset(ACCSECPitchers, TaggedPitchType == "CT" & PitcherThrows == "Left")
```


```{r}
## Boxplots WAKE VELOCITY
ggplot(WAKE_RHP_FF, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP FF - Velocity", x = "Velocity")

ggplot(WAKE_LHP_FF, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP FF - Velocity", x = "Velocity")

ggplot(WAKE_RHP_FT, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP FT - Velocity", x = "Velocity")

ggplot(WAKE_LHP_FT, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP FT - Velocity", x = "Velocity")

ggplot(WAKE_RHP_SL, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP SL - Velocity", x = "Velocity")

ggplot(WAKE_LHP_SL, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP SL - Velocity", x = "Velocity")

ggplot(WAKE_RHP_CB, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP CB - Velocity", x = "Velocity")

ggplot(WAKE_LHP_CB, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP CB - Velocity", x = "Velocity")

ggplot(WAKE_RHP_CH, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP CH - Velocity", x = "Velocity")

ggplot(WAKE_LHP_CH, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP CH - Velocity", x = "Velocity")
```


```{r}
## Boxplots ACCSEC VELOCITY
ggplot(ACCSEC_RHP_FF, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP FF - Velocity", x = "Velocity")

ggplot(ACCSEC_LHP_FF, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP FF - Velocity", x = "Velocity")

ggplot(ACCSEC_RHP_FT, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP FT - Velocity", x = "Velocity")

ggplot(ACCSEC_LHP_FT, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP FT - Velocity", x = "Velocity")

ggplot(ACCSEC_RHP_SL, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP SL - Velocity", x = "Velocity")

ggplot(ACCSEC_LHP_SL, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP SL - Velocity", x = "Velocity")

ggplot(ACCSEC_RHP_CB, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP CB - Velocity", x = "Velocity")

ggplot(ACCSEC_LHP_CB, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP CB - Velocity", x = "Velocity")

ggplot(ACCSEC_RHP_CH, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP CH - Velocity", x = "Velocity")

ggplot(ACCSEC_LHP_CH, aes(x=RelSpeed)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP CH - Velocity", x = "Velocity")
```


```{r}
## Boxplots WAKE HORZBREAK
ggplot(WAKE_RHP_FF, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP FF - HorzBreak", x = "HorzBreak")

ggplot(WAKE_LHP_FF, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP FF - HorzBreak", x = "HorzBreak")

ggplot(WAKE_RHP_FT, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP FT - HorzBreak", x = "HorzBreak")

ggplot(WAKE_LHP_FT, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP FT - HorzBreak", x = "HorzBreak")

ggplot(WAKE_RHP_SL, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP SL - HorzBreak", x = "HorzBreak")

ggplot(WAKE_LHP_SL, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP SL - HorzBreak", x = "HorzBreak")

ggplot(WAKE_RHP_CB, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP CB - HorzBreak", x = "HorzBreak")

ggplot(WAKE_LHP_CB, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP CB - HorzBreak", x = "HorzBreak")

ggplot(WAKE_RHP_CH, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP CH - HorzBreak", x = "HorzBreak")

ggplot(WAKE_LHP_CH, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP CH - HorzBreak", x = "HorzBreak")
```


```{r}
## Boxplots ACCSEC HorzBreak
ggplot(ACCSEC_RHP_FF, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP FF - HorzBreak", x = "HorzBreak")

ggplot(ACCSEC_LHP_FF, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP FF - HorzBreak", x = "HorzBreak")

ggplot(ACCSEC_RHP_FT, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP FT - HorzBreak", x = "HorzBreak")

ggplot(ACCSEC_LHP_FT, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP FT - HorzBreak", x = "HorzBreak")

ggplot(ACCSEC_RHP_SL, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP SL - HorzBreak", x = "HorzBreak")

ggplot(ACCSEC_LHP_SL, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP SL - HorzBreak", x = "HorzBreak")

ggplot(ACCSEC_RHP_CB, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP CB - HorzBreak", x = "HorzBreak")

ggplot(ACCSEC_LHP_CB, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP CB - HorzBreak", x = "HorzBreak")

ggplot(ACCSEC_RHP_CH, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP CH - HorzBreak", x = "HorzBreak")

ggplot(ACCSEC_LHP_CH, aes(x=HorzBreak)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP CH - HorzBreak", x = "HorzBreak")
```


```{r}
## Boxplots WAKE InducedVertBreak
ggplot(WAKE_RHP_FF, aes(x=InducedVertBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP FF - InducedVertBreak", x = "InducedVertBreak")

ggplot(WAKE_LHP_FF, aes(x=InducedVertBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP FF - InducedVertBreak", x = "InducedVertBreak")

ggplot(WAKE_RHP_FT, aes(x=InducedVertBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP FT - InducedVertBreak", x = "InducedVertBreak")

ggplot(WAKE_LHP_FT, aes(x=InducedVertBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP FT - InducedVertBreak", x = "InducedVertBreak")

ggplot(WAKE_RHP_SL, aes(x=InducedVertBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP SL - InducedVertBreak", x = "InducedVertBreak")

ggplot(WAKE_LHP_SL, aes(x=InducedVertBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP SL - InducedVertBreak", x = "InducedVertBreak")

ggplot(WAKE_RHP_CB, aes(x=InducedVertBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP CB - InducedVertBreak", x = "InducedVertBreak")

ggplot(WAKE_LHP_CB, aes(x=InducedVertBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP CB - InducedVertBreak", x = "InducedVertBreak")

ggplot(WAKE_RHP_CH, aes(x=InducedVertBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP CH - InducedVertBreak", x = "InducedVertBreak")

ggplot(WAKE_LHP_CH, aes(x=InducedVertBreak)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP CH - InducedVertBreak", x = "InducedVertBreak")
```


```{r}
## Boxplots WAKE SpinAxis
ggplot(WAKE_RHP_FF, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP FF - SpinAxis", x = "SpinAxis")

ggplot(WAKE_LHP_FF, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP FF - SpinAxis", x = "SpinAxis")

ggplot(WAKE_RHP_FT, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP FT - SpinAxis", x = "SpinAxis")

ggplot(WAKE_LHP_FT, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP FT - SpinAxis", x = "SpinAxis")

ggplot(WAKE_RHP_SL, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP SL - SpinAxis", x = "SpinAxis")

ggplot(WAKE_LHP_SL, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP SL - SpinAxis", x = "SpinAxis")

ggplot(WAKE_RHP_CB, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP CB - SpinAxis", x = "SpinAxis")

ggplot(WAKE_LHP_CB, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP CB - SpinAxis", x = "SpinAxis")

ggplot(WAKE_RHP_CH, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="Wake RHP CH - SpinAxis", x = "SpinAxis")

ggplot(WAKE_LHP_CH, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="Wake LHP CH - SpinAxis", x = "SpinAxis")
```


```{r}
## Boxplots ACCSEC SpinAxis
ggplot(ACCSEC_RHP_FF, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP FF - SpinAxis", x = "SpinAxis")

ggplot(ACCSEC_LHP_FF, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP FF - SpinAxis", x = "SpinAxis")

ggplot(ACCSEC_RHP_FT, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP FT - SpinAxis", x = "SpinAxis")

ggplot(ACCSEC_LHP_FT, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP FT - SpinAxis", x = "SpinAxis")

ggplot(ACCSEC_RHP_SL, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP SL - SpinAxis", x = "SpinAxis")

ggplot(ACCSEC_LHP_SL, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP SL - SpinAxis", x = "SpinAxis")

ggplot(ACCSEC_RHP_CB, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP CB - SpinAxis", x = "SpinAxis")

ggplot(ACCSEC_LHP_CB, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP CB - SpinAxis", x = "SpinAxis")

ggplot(ACCSEC_RHP_CH, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC RHP CH - SpinAxis", x = "SpinAxis")

ggplot(ACCSEC_LHP_CH, aes(x=SpinAxis)) + geom_boxplot(fill='Gold') +
  labs(title="ACCSEC LHP CH - SpinAxis", x = "SpinAxis")
```


```{r}
ALLData <- rbind(WAKE_RHP_FF, WAKE_LHP_FF, WAKE_RHP_FT, WAKE_LHP_FT, WAKE_RHP_CB, WAKE_LHP_CB, WAKE_RHP_SL, WAKE_LHP_SL, WAKE_RHP_CH, WAKE_LHP_CH, ACCSEC_RHP_FF, ACCSEC_LHP_FF, ACCSEC_RHP_FT, ACCSEC_LHP_FT, ACCSEC_RHP_CB, ACCSEC_LHP_CB, ACCSEC_RHP_SL, ACCSEC_LHP_SL, ACCSEC_RHP_CH, ACCSEC_LHP_CH, WAKE_RHP_CT, WAKE_LHP_CT, ACCSEC_RHP_CT, ACCSEC_LHP_CT)
```

